api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from api.views import   CategoryViewSet, OrderViewSet, api_product, api_products, hello_world, hello_world_drf
from rest_framework.routers import DefaultRouter

#dev_48 app/urls.py 추가
app_name = 'api'

#dev_54
router = DefaultRouter()
router.register(r'categories',CategoryViewSet)
#dev_58
router.register("orders", OrderViewSet, basename="orders")

# /post/ 주소에 대해 URL Reverse 이름은 post-list이 등록
# /post/10/ 류의 주소에 대해 URL Reverse 이름은 post-detail이 등록


urlpatterns = [
    path("hello_world/", hello_world),
    path("hello_world_drf/", hello_world_drf),
    path("products/", api_products),#dev_49
    path("products/<int:pk>/", api_product),#dev_49
    path("products/", api_products),
    path("products/<int:pk>/", api_product),
    #path("categories/", MixinsCategories.as_view()),#dev_52
    #path("categories/<int:pk>/", MixinsCategory.as_view()),#dev_52         
    #path("categories/", APICategories.as_view()),#dev_53
    #path("categories/<int:pk>/", APICategory.as_view()),#dev_53
    #path("categories/", category_list),#dev_54
    #path("categories/<int:pk>/", category_detail),#dev_54
    path("", include(router.urls)),#dev_54
]

cart/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from cart import views

app_name = 'cart'

urlpatterns = [
    path("", views.cart_summary,name="cart_summary"),
    path("add/", views.cart_add,name="cart_add"), 
    path("delete/", views.cart_delete,name="cart_delete"), 
    path("update/", views.cart_update,name="cart_update"),      
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('store.urls')),
    path("home/", include('home.urls')),
    path("boards/", include('boards.urls')),
    path('account/', include('accounts.urls')),
    path("cart/", include('cart.urls')), 
    path("payment/", include('payment.urls')), #dev_41 settings 추가
    path('accounts/', include('allauth.urls')),#dev_46 
    path("api/", include("api.urls")),#dev_48
    path("auth/", include('djoser.urls')),#dev_57
    path("auth/", include('djoser.urls.jwt')),#dev_57
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

#dev_42
app_name = 'payment'

#dev_41 url 추가
# Create your views here.
urlpatterns = [
    path("payment_update_info/", views.payment_update_info, name="payment_update_info"), #dev_42 추가
    path("payment_success/", views.payment_success, name="payment_success"),
    path("payment_process_order/", views.payment_process_order, name="payment_process_order"),
    path("payment_order_list/", views.payment_order_list, name="payment_order_list"), #dev_45 추가
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),  
    path('about/', views.about, name='about'),
    path('product/<int:product_id>', views.product, name='product'),
    path('category/<str:foo>', views.category, name='category'), #변수 foo 의 의미  참고:https://namu.wiki/w/foo
    path('category_summary/', views.category_summary, name='category_summary'),
    #dev_39
    path('search/', views.search, name='search'),
]

cart/models.py
from django.db import models

#dev_40
# Create your models here.
class Cart(models.Model):
    user  = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"카트아이디:{self.id}    유저이름:{self.user.username}"
    

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE,related_name='cart_items')
    product = models.ForeignKey('store.Product', on_delete=models.CASCADE,related_name='items')
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"자기아이디:{self.id}    카트아이디:{self.cart.id}   제품아이디:{self.product.id}   제품이름:{self.product.name}   제품수량:{self.quantity}"

cart/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.shortcuts import render

from cart.cart import Cart
from store.models import Product
from django.contrib import messages

def cart_summary(request):
    # Get the cart
    cart = Cart(request)
    cart_products = cart.get_prods()
    quantities = cart.get_quants
    
    # 추가
    totals = cart.cart_total()
    
    return render(request, "cart/cart_summary.html",{"cart_products": cart_products,"quantities": quantities,"totals": totals})


def cart_add(request):
    
    cart  = Cart(request)

    if request.POST.get('action') == 'post':
        
        #get stuff
        product_id = int(request.POST.get('product_id'))
        print('product_id', product_id)
        
        product_qty = int(request.POST.get('product_qty'))
        # lookup proudct in DB
        product = get_object_or_404(Product,id=product_id)

        print("프로덕트",product)

        #save to session
        #cart.add(product=product, quantity = product_qty)
        #dev_40 DB 저장모듈 추가
        cart.add_to_cart(product=product, quantity = product_qty)



        #Get Cart Quantity
        cart_quantity = cart.__len__()
        response = JsonResponse({'qty': cart_quantity})
        #추가 dev_38
        messages.success(request,"장바구니에 해당 상품이 추가되었습니다.")
        return response
    

def cart_delete(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        
        #get stuff
        product_id = int(request.POST.get('product_id'))
        print('product_id =============== ', product_id)

        cart.delete(product=product_id)

        response = JsonResponse({'product':product_id})
        messages.success(request,"장바구니에서 해당 상품이 삭제되었습니다.")
        return response

def cart_update(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        
        #get stuff
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        cart.update(product=product_id, quantity=product_qty)
        response = JsonResponse({'qty':product_qty})
        #추가 dev_38
        messages.success(request,"장바구니가 업데이트 되었습니다.")        
        return response

templates/cart/cart_head.html
{% load static %}

<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <title>cart</title>
  <!-- Bootstrap icons-->
  {% comment %} <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" rel="stylesheet"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" rel="stylesheet"/> {% endcomment %}
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'cart/css/styles.css' %}" rel="stylesheet"/>
  <!-- jQuery -->

</head>

templates/cart/cart_summary.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}

  {% comment %} #dev_47 head 수정 {% endcomment %}
  {% include 'payment/head.html' %}
  
  {% comment %} dev_47 {% endcomment %}
  <script>

    var impCode = 'imp43216235';

    function handlePayment(pg, pay_method){
      console.log("handlePayment");
      console.log(pg);
      console.log(payMethod);

      // 결제하기 버튼 클릭 시 결제 요청
      IMP.init(impCode);
      IMP.request_pay({
          pg: pg,
          pay_method: payMethod,
          //merchant_uid: '212R3A11TD233AAC', // 주문번호 생성(생략시 포트원에서 자동생성)
          name: '상품1', //결제창에 노출될 상품명
          amount: 3000, // 결제 가격
          buyer_name: '김민규',
          buyer_tel: '010-1234-5678'
        }, function(rsp) {
            if (rsp.success) {
                // 결제 성공 시
                $.ajax({
                    type: 'POST',
                    url: 'api/v1/payment/validation/' + rsp.imp_uid
                }).done(function(data) {
                    console.log(data);
                    if (order.price == data.response.amount) {
                        order.impUid = rsp.imp_uid;
                        order.merchantUid = rsp.merchant_uid;
                        // 결제 금액 일치. 결제 성공 처리
                        $.ajax({
                            url: "api/v1/payment/order",
                            method: "post",
                            data: JSON.stringify(order),
                            contentType: "application/json"
                        }).then(function(res) {
                            console.log("res", res);
                            console.log("rsp", rsp);
                            var msg = '결제가 완료되었습니다.';
                            msg += '고유ID : ' + rsp.imp_uid;
                            msg += '상점 거래ID : ' + rsp.merchant_uid;
                            msg += '결제 금액 : ' + rsp.paid_amount;
                            msg += '카드 승인번호 : ' + rsp.apply_num;
                            alert(msg);
                        }).catch(function(error) {
                            alert("주문정보 저장을 실패 했습니다.");
                        });
                    }
                }).catch(function(error) {
                    alert('결제에 실패하였습니다. ' + rsp.error_msg);
                });
            } else {
                alert(rsp.error_msg);
            }
        });
    }
  </script>


  <!-- 네비게이션바 -->
  {% include "layout/navbar.html" %}

  <header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">장바구니</h1>
        <p class="lead fw-normal text-white-50 mb-0">View your Cart</p>
      </div>
    </div>
  </header>

  <br/>

  <div class="container">
    {% if cart_products%}
      {% for product in cart_products %}
        <form action="{% url 'payment:payment_process_order'%}" method="post">
          {% csrf_token %}
          <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
                <img src=" {{product.image.url}}" style="width:100%;height:18rem;object-fit:fill" class="img-fluid rounded-start" alt="..."/>
              </div>
              <div class="col-md-8">
                <div class="card-body mt-4">
                  <center>
                    <h5 class="card-title">{{product.name}}</h5>
                    <p class="card-text">{{product.description}}</p>

                    {% if product.is_sale%}

                      <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                      </div>
                      <!-- Product price-->
                      <strike>
                        ${{ product.price }}
                      </strike>
                      &nbsp; ${{product.sale_price}}
                    {% else %}
                      ${{ product.price }}
                      <br/>
                      ID :
                      {{product.id}}
                      {%endif%}
                      <br/><br/>
                      <div class="row justify-content-center">
                        <div class="col-md-2">Quantity</div>
                        <div class="col-md-2">
                          <select class="form-select form-select-sm" id="select{{product.id}}" aria-label="Default select example">
                            {% for key, value in quantities.items %}
                              {% if key == product.id|slugify%}
                                <option selected="selected">{{ value }}</option>
                              {% endif %}
                            {% endfor %}
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                          </select>
                        </div>
                      </div>
                      <br/>
                      <a href="{% url 'store:home' %}" class="btn btn-secondary">홈으로</a>
                      {% comment %} <button type="button" value="{{product.id}}" id="add-cart" class="btn btn-secondary">Add to Cart</button> {% endcomment %}
                      <button type="button" data-index="{{product.id}}" class="btn btn-secondary update-cart">업데이트</button>
                      <button type="button" data-index="{{product.id}}" class="btn btn-danger delete-product">삭제</button>
                    </center>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          {% comment %} #dev_43 {% endcomment %}
        </form>
        {% comment %} #dev_47 임시로 {% endcomment %}
        <div class="text-center">
          <h3 id="totals" data-totals="{{totals}}">Total:{{totals}}원</h3>
          {% comment %} <a class="btn btn-success text-center" href="{% url 'payment:payment_process_order'%}">주문</a> {% endcomment %}
          {% comment %} <button id="cardPay" onclick="handlePayment('html5_inicis.INIpayTest', 'card')" type="submit" class="btn btn-success text-center" >카드결제</button>
          <button id="kakaoPay" onclick="handlePayment('kakaopay', 'card')" type="submit" class="btn btn-success text-center" >카카오페이</button> {% endcomment %}
          <button id="cardPay" data-pg="html5_inicis.INIpayTest" data-pay="card"  class="btn btn-success text-center request-pay" >카드결제</button>
          <button id="kakaoPay" data-pg="kakaopay" data-pay="card" class="btn btn-success text-center request-pay" >카카오페이</button>
        </div>
        <br />
        <br />
        <br />
      {% else %}
        There's Nothing in your cart
      {% endif %}
    </div>

    <script>

      $(document).on('click', '.request-pay', function (e) {
        let pg = $(this).data('pg');
        let payMethod = $(this).data('pay');
        let priceTotals = $("#totals").data('totals');        

        // 결제하기 버튼 클릭 시 결제 요청
        IMP.init(impCode);
        IMP.request_pay({
          pg: pg,
          pay_method: payMethod,
          //merchant_uid: '212R3A11TD233AAC', // 주문번호 생성(생략시 포트원에서 자동생성)
          name: '장바구니 주문', //결제창에 노출될 상품명
          //amount: priceTotals, // 결제 가격
          amount: 10,//테스트를 위하여 10원으로 설정
          buyer_name: '{{user.username}}', // 구매자 이름
          buyer_tel: '010-1234-5678',
          buyer_email: '{{user.email}}', // 구매자 이메일,
          //buyer_addr : buyerAddress, // 구매자 주소
          //buyer_postcode : '123-456', // 임의의 값
        }, function(rsp) {
            if (rsp.success) {
                // 결제 성공 시
                console.log(rsp);
                console.log("결재성공");                
                
                // 결제 성공 시 로직
                //1.주문 정보 저장을 위해 ajax 요청
                //2.서버에서 결재금액과 주문금액(세션에 저장되어있는)이 일치하는지 확인
                //3.일치하면 주문 정보 및 결재정보 저장
                $.ajax({
                  type: 'POST',
                  url: '{% url "payment:payment_process_order" %}',
                  data: {
                    imp_uid: rsp.imp_uid, //결재아이디(포트원에서 생성된 고유값)
                    paid_amount: rsp.paid_amount, //결재 금액                    
                    csrfmiddlewaretoken: '{{  csrf_token }}',
                    action: 'post'
                  },
                  success: function (response) {
                    console.log(response);
                    if(response == 'SUCCESS') {
                      alert('결제가 완료되었습니다.');
                      location.href = '/';
                    }else {
                      alert('결제에 실패하였습니다');
                      location.reload();
                    }
                    
                  },
                  error: function (e) {
                    alert('결제에 실패하였습니다. ' + rsp.error_msg);
                  }
                });
              } else {
                alert(rsp.error_msg);
              }
        });

      });


      $(document).on('click', '.update-cart', function (e) {
        let productid = $(this).data('index');
        let qty = $('#select' + productid + ' ' + 'option:selected').text();

        $.ajax({
          type: 'POST',
          url: '{% url "cart:cart_update" %}',
          data: {
            product_id: $(this).data('index'),
            product_qty: qty,
            csrfmiddlewaretoken: '{{  csrf_token }}',
            action: 'post'
          },
          success: function (json) {
            console.log(json);
            location.reload();
          },
          error: function (e) {
            console.log(e);
          }
        });
      });

      $(document).on('click', '.delete-product', function (e) {
        let productid = $(this).data('index');
    
        $.ajax({
          type: 'POST',
          url: '{% url "cart:cart_delete" %}',
          data: {
            product_id: $(this).data('index'),    
            csrfmiddlewaretoken: '{{  csrf_token }}',
            action: 'post',
          },
          success: function (json) {
            console.log(json);
            location.reload(); //페이지 새로 고침
          },
          error: function (e) {
            console.log(e);
          },
        });
      });
    </script>
  {%endblock content%}

templates/cart/cart_summary2.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}
  {% include 'store/head.html' %}
  <!-- 네비게이션바 -->
  {% include "layout/navbar.html" %}

  <header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">장바구니</h1>
        <p class="lead fw-normal text-white-50 mb-0">View your Cart</p>
      </div>
    </div>
  </header>
  <br/>
  {% include 'cart/cart_head.html' %}
  <div class="cart-body">
    <div class="container">
      <div class="card">
        <div class="row">
          <div class="col-md-8 cart">
            <div class="title">
              <div class="row">
                <div class="col">
                  <h4>
                    <b>Shopping Cart</b>
                  </h4>
                </div>
                <div class="col align-self-center text-right text-muted">3 items</div>
              </div>
            </div>
            <div class="row border-top border-bottom">
              <div class="row main align-items-center">
                <div class="col-2"><img class="img-fluid" src="https://i.imgur.com/1GrakTl.jpg"></div>
                <div class="col">
                  <div class="row text-muted">Shirt</div>
                  <div class="row">Cotton T-shirt</div>
                </div>
                <div class="col">
                  <a href="#">-</a>
                  <a href="#" class="border">1</a>
                  <a href="#">+</a>
                </div>
                <div class="col">&euro; 44.00
                  <span class="close">&#10005;</span></div>
              </div>
            </div>
            <div class="row">
              <div class="row main align-items-center">
                <div class="col-2"><img class="img-fluid" src="https://i.imgur.com/ba3tvGm.jpg"></div>
                <div class="col">
                  <div class="row text-muted">Shirt</div>
                  <div class="row">Cotton T-shirt</div>
                </div>
                <div class="col">
                  <a href="#">-</a>
                  <a href="#" class="border">1</a>
                  <a href="#">+</a>
                </div>
                <div class="col">&euro; 44.00
                  <span class="close">&#10005;</span></div>
              </div>
            </div>
            <div class="row border-top border-bottom">
              <div class="row main align-items-center">
                <div class="col-2"><img class="img-fluid" src="https://i.imgur.com/pHQ3xT3.jpg"></div>
                <div class="col">
                  <div class="row text-muted">Shirt</div>
                  <div class="row">Cotton T-shirt</div>
                </div>
                <div class="col">
                  <a href="#">-</a>
                  <a href="#" class="border">1</a>
                  <a href="#">+</a>
                </div>
                <div class="col">&euro; 44.00
                  <span class="close">&#10005;</span></div>
              </div>
            </div>
            <div class="back-to-shop">
              <a href="#">&leftarrow;</a>
              <span class="text-muted">Back to shop</span></div>
          </div>
          <div class="col-md-4 summary">
            <div>
              <h5>
                <b>Summary</b>
              </h5>
            </div>
            <hr>
            <div class="row">
              <div class="col" style="padding-left:0;">ITEMS 3</div>
              <div class="col text-right">&euro; 132.00</div>
            </div>
            <form>
              <p>SHIPPING</p>
              <select>
                <option class="text-muted">Standard-Delivery- &euro;5.00</option>
              </select>
              <p>GIVE CODE</p>
              <input id="code" placeholder="Enter your code">
            </form>
            <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
              <div class="col">TOTAL PRICE</div>
              <div class="col text-right">&euro; 137.00</div>
            </div>
            <button class="btn">CHECKOUT</button>
          </div>
        </div>

      </div>
    </div>
  </div>
{%endblock content%}