api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from api.views import   CategoryViewSet, OrderViewSet, api_product, api_products, hello_world, hello_world_drf
from rest_framework.routers import DefaultRouter

#dev_48 app/urls.py 추가
app_name = 'api'

#dev_54
router = DefaultRouter()
router.register(r'categories',CategoryViewSet)
#dev_58
router.register("orders", OrderViewSet, basename="orders")

# /post/ 주소에 대해 URL Reverse 이름은 post-list이 등록
# /post/10/ 류의 주소에 대해 URL Reverse 이름은 post-detail이 등록


urlpatterns = [
    path("hello_world/", hello_world),
    path("hello_world_drf/", hello_world_drf),
    path("products/", api_products),#dev_49
    path("products/<int:pk>/", api_product),#dev_49
    path("products/", api_products),
    path("products/<int:pk>/", api_product),
    #path("categories/", MixinsCategories.as_view()),#dev_52
    #path("categories/<int:pk>/", MixinsCategory.as_view()),#dev_52         
    #path("categories/", APICategories.as_view()),#dev_53
    #path("categories/<int:pk>/", APICategory.as_view()),#dev_53
    #path("categories/", category_list),#dev_54
    #path("categories/<int:pk>/", category_detail),#dev_54
    path("", include(router.urls)),#dev_54
]

boards/urls.py
from django.contrib import admin
from django.urls import path

from .views import base_views,comment_views,post_views
app_name = 'boards'

urlpatterns = [
   # base_views.py
   path("", base_views.index,name='index'), #boards/ 끝에 슬러시 주의 할것
   path('<int:post_id>/', base_views.detail, name='detail'),
   
   #comment_views.py
   path('comment/create/<int:post_id>/', comment_views.comment_create, name='reply_create'),
   path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
   path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),
   path('comment/vote/<int:comment_id>/', comment_views.comment_vote, name='comment_vote'),

   #post_views
   path('post/create/', post_views.post_create, name='post_create'),
   path('post/modify/<int:post_id>/', post_views.post_modify, name='post_modify'),
   path('post/delete/<int:post_id>/', post_views.post_delete, name='post_delete'),
   path('post/vote/<int:post_id>/', post_views.post_vote, name='post_vote'),

]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('store.urls')),
    path("home/", include('home.urls')),
    path("boards/", include('boards.urls')),
    path('account/', include('accounts.urls')),
    path("cart/", include('cart.urls')), 
    path("payment/", include('payment.urls')), #dev_41 settings 추가
    path('accounts/', include('allauth.urls')),#dev_46 
    path("api/", include("api.urls")),#dev_48
    path("auth/", include('djoser.urls')),#dev_57
    path("auth/", include('djoser.urls.jwt')),#dev_57
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='user_post') 
    voter = models.ManyToManyField(User,related_name='voter_post') 
    title = models.CharField(max_length=128, verbose_name='제목')
    hit = models.PositiveIntegerField(verbose_name='조회수', default=0)
    image_url   = models.URLField(max_length=500,blank=True,null=True)
    content     = models.TextField(null=True)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.id} {self.title}"

    

# 댓글 관련 테이블
class Comment(models.Model):
    user       = models.ForeignKey(User, on_delete=models.CASCADE,related_name='user_comment')
    voter = models.ManyToManyField(User, related_name='voter_comment')
    post       = models.ForeignKey(Post, on_delete=models.CASCADE)
    content    = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id} {self.content}"
    

boards/forms.py
from django import forms
from boards.models import Comment, Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post  # 사용할 모델
        fields = ['title', 'content']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # } 
        labels = {
            'title': '제목',
            'content': '내용',
        } 

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  # 사용할 모델
        fields = ['content']
        labels = {
            'content': '댓글',
        }   

boards/views/base_views.py
from django.http import HttpResponseNotAllowed
from django.utils import timezone   
from django.shortcuts import get_object_or_404, redirect, render

from boards.forms import CommentForm, PostForm
from boards.models import Comment, Post
from django.core.paginator import Paginator 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q

def index(request):
    page = request.GET.get('page', '1')  # 페이지 만약 넘어온값이 없으면 1페이지
    
    kw = request.GET.get('kw', '')  # 검색어 넘어온값이 없으면 ''(빈값으로)   
    post_list = Post.objects.order_by('-created_at')
    
    if kw:
        post_list = post_list.filter(
            Q(title__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw)|  # 내용 검색
            Q(comment__content__icontains=kw) |  # 답변 내용 검색
            Q(user__username__icontains=kw) |  # 게시글 글쓴이 검색
            Q(comment__user__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct() # 중복 제거

    paginator = Paginator(post_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'post_list': page_obj,'page': page, 'kw': kw} 

    return render(request, 'boards/post_list.html', context)

def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {'post': post}
    return render(request, 'boards/post_detail.html', context)

boards/views/comment_views.py
from django.http import HttpResponseNotAllowed
from django.utils import timezone   
from django.shortcuts import get_object_or_404, redirect, render

from boards.forms import CommentForm, PostForm
from boards.models import Comment, Post
from django.core.paginator import Paginator 
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='accounts:login')
def comment_create(request,post_id):
    """
    댓글 등록
    """
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        
        if form.is_valid(): # 폼이 유효하다면
            comment = form.save(commit=False) # 임시 저장하여 post 객체를 리턴받는다.
            comment.user = request.user
            comment.post = post
            comment.save()# 데이터를 실제로 저장한다.
            return redirect('boards:index')
    else:
        return HttpResponseNotAllowed('Only POST is possible.')

    context = {'post':post,'form': form}
    return render(request, 'boards/post_form.html', context)


@login_required(login_url='boards:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    
    if request.user != comment.user:
        messages.error(request, '수정권한이 없습니다')
        return redirect('boares:detail', comment_id=comment.post.id)
    
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            #answer.modify_date = timezone.now()
            comment.save()
            return redirect('boards:detail', post_id=comment.post.id)
    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'boards/comment_form.html', context)

@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.user:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('boards:detail', post_id=comment.post.id)
    comment.delete()
    return redirect('boards:detail', post_id=comment.post.id)

@login_required(login_url='accounts:login')
def comment_vote(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    
    if request.user == comment.user:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        comment.voter.add(request.user)
    
    return redirect('boards:detail', post_id=comment.post.id)

boards/views/post_views.py
from django.http import HttpResponseNotAllowed
from django.utils import timezone   
from django.shortcuts import get_object_or_404, redirect, render

from boards.forms import CommentForm, PostForm
from boards.models import Comment, Post
from django.core.paginator import Paginator 
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='accounts:login')
def post_create(request):

    if request.method == 'POST':
        form = PostForm(request.POST)
        
        if form.is_valid(): # 폼이 유효하다면
            post = form.save(commit=False) # 임시 저장하여 post 객체를 리턴받는다.
            post.user = request.user  # author 속성에 로그인 계정 저장
            post.save()# 데이터를 실제로 저장한다.
            return redirect('boards:index')
    else:
        form = PostForm()

    context = {'form': form}
    return render(request, 'boards/post_form.html', context)

@login_required(login_url='accounts:login')
def post_modify(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    if request.user != post.user:
        messages.error(request, '수정권한이 없습니다')
        return redirect('boards:detail', post_id=post.id)
    
    if request.method == "POST":
        form = PostForm(request.POST, instance=post) 
        if form.is_valid():
            post = form.save(commit=False)
            #post.modify_date = timezone.now()  # 수정일시 저장
            post.save()
            return redirect('boards:detail', post_id=post.id)
    else:
        form = PostForm(instance=post) #GET 요청인 경우 질문수정 화면에 조회된 질문의 제목과 내용이 반영될 수 있도록 다음과 같이 폼을 생성해야 한다.
    
    context = {'form': form}
    return render(request, 'boards/post_form.html', context)

@login_required(login_url='accounts:login')
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.user:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('boards:detail', post_id=post.id)
    post.delete()
    return redirect('boards:index')

@login_required(login_url='accounts:login')
def post_vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user == post.user:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        post.voter.add(request.user)
    return redirect('boards:detail', post_id=post.id)

templates/boards/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> {% endcomment %}
    <title>Hello World</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/boards/comment_form.html
{% extends 'layout/base.html' %}
{% block content %}
  {% include 'store/head.html' %}
  <!-- 네비게이션바 -->
  {% include "layout/navbar.html" %}
  <!-- Header -->
  {% include 'store/header.html' %}
  <!-- 답변 수정-->
  <div class="container my-3">
    <form method="post">
      {% csrf_token %}
      {% include "layout/form_errors.html" %}
      <div class="mb-3">
        <label for="content" class="form-label">답변내용</label>
        <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
      </div>
      <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
  </div>
{% endblock %}

templates/boards/for_loop.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>Document</title>
  </head>

  <body>
    <h1>Template Language!</h1>
    <p>{{post_list}}</p>
    {% for i in post_list %}
      <div>번호 :{{forloop.counter}}번째 data</div>
      <div>제목 :{{i.title}}</div>
      {% if i.hit == 0 %}
        <div>조회수 :{{i.hit}}</div>
        {%else%}
        <div>조회수가 0 초과 입니다. :{{i.hit}}</div>
        {%endif%}
        <div>내용 :{{i.content}}</div>
        <br/>
      {% endfor %}
      <p>
        <div>price 출력 :
          {{price}}</div>
        <div>l의 0번째 값은 :
          {{price.0}}</div>
        <div>l의 1번째 값은 :
          {{price.1}}</div>
        <div>l의 2번째 값은 :
          {{price.2}}</div>
      </p>
      <p>
        <div>name 출력 :
          {{name}}</div>
        <div>name의 key(name) 값은 :
          {{name.name}}</div>
        <div>name의 key(age)) 값은 :
          {{name.age}}</div>
        <div>name의 key(location) 값은 :
          {{name.location}}</div>
        <div>name의 key(isman) 값은 :
          {{name.isman}}</div>
      </p>
      <br>
      <h1>Template Language!</h1>
      {% with value='hello Django'%}
      <h4>{{value}}</h4>
      {% endwith %}
      {% lorem %}
      <!-- 👈 lorem 생성 -->
      {% lorem 3 p%}
      <!-- 👈 lorem 문장(p)을 3개 생성 -->
      {% lorem 2 w random %}
      {% lorem 5 w random %}
      <!-- 👈 lorem 단어(w)을 5개 랜덤 생성 -->

    </body>

  </html>

templates/boards/post_detail.html
{% extends 'layout/base.html' %}
{% block content %}
{% include 'store/head.html' %}
<!-- 네비게이션바 -->
{% include "layout/navbar.html" %}    
<!-- Header -->  
{% include 'store/header.html' %}

<div class="container my-3">
  <!-- message 표시 -->
  {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
  {% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul><li>{{ message.message }}</li></ul>
  {% endfor %}
    </div>
  {% endif %}
  <!-- 부모글 -->
  <h2 class="border-bottom py-2">{{ post.title }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
      <div class="d-flex justify-content-end">
        {% if post.updated_at %}
        <div class="badge bg-light text-dark p-2 text-start mx-3">
            <div class="mb-2">수정 시간</div>
            <div>{{ post.updated_at }}</div>
        </div>
        {% endif %}
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ post.user.username }}</div>
          <div>{{ post.created_at }}</div>
        </div>
      </div>
      <div class="my-3">
        <a href="javascript:void(0)" data-uri="{% url 'boards:post_vote' post.id  %}"
          class="recommend btn btn-sm btn-outline-secondary"> 추천
         <span class="badge rounded-pill bg-success">{{post.voter.count}}</span>
        </a>
        {% if request.user == post.user %}
        <a href="{% url 'boards:post_modify' post.id  %}" 
           class="btn btn-sm btn-outline-secondary">수정</a>
           <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
           data-uri="{% url 'boards:post_delete' post.id  %}">삭제</a>
        {% endif %}
      </div>
    </div>
  </div>

  <!-- 댓글목록 -->
  <h5 class="border-bottom my-3 py-2">{{post.comment_set.count}}개의 댓글이 있습니다.</h5>
  {% for comment in post.comment_set.all %}
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
        <div class="d-flex justify-content-end">
          {% if comment.updated_at %}
          <div class="badge bg-light text-dark p-2 text-start mx-3">
              <div class="mb-2">수정시간</div>
              <div>{{ comment.updated_at }}</div>
          </div>
          {% endif %}

          <div class="badge bg-light text-dark p-2 text-start">
            <div class="mb-2">{{ comment.user.username }}</div>
             <div>{{comment.created_at}}</div>
          </div>
        </div>
        <div class="my-3">
          <a href="javascript:void(0)" data-uri="{% url 'boards:comment_vote' comment.id  %}"
          class="recommend btn btn-sm btn-outline-secondary"> 추천
           <span class="badge rounded-pill bg-success">{{comment.voter.count}}</span>
          </a>
          {% if request.user == comment.user %}
          <a href="{% url 'boards:comment_modify' comment.id  %}" 
             class="btn btn-sm btn-outline-secondary">수정</a>
          <a href="#" class="delete btn btn-sm btn-outline-secondary "
             data-uri="{% url 'boards:comment_delete' comment.id  %}">삭제</a>
          {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}

  <!-- 댓글등록 -->
  {% comment %} <form action="{% url 'boards:reply_create' post.id %}" method="post">
    {% csrf_token %}
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="댓글등록">
  </form> {% endcomment %}
  <form action="{% url 'boards:reply_create' post.id %}" method="post" class="my-3">
    {% csrf_token %}
    <!-- 오류표시 Start -->
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
          {% for field in form %}
            {% if field.errors %}
              <div>
              <strong>{{ field.label }}</strong>
                      {{ field.errors }}
              </div>
            {% endif %}
          {% endfor %}
      </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="mb-3">
        <label for="content" class="form-label">답변내용</label>
        <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="댓글등록" class="btn btn-primary">
</form>
</div>
{%endblock%}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/boards/post_form.html
{% extends 'layout/base.html' %}
{% block content %}
{% include 'store/head.html' %}
<!-- 네비게이션바 -->
{% include "layout/navbar.html" %}    
<!-- Header -->  
{% include 'store/header.html' %}
  <div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글등록</h5>
    <form method="post">
      {% csrf_token %}
      <!-- 오류표시 Start -->
      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for field in form %}
            {% if field.errors %}
              <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
              </div>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
      <!-- 오류표시 End -->
      <div class="mb-3">
        <label for="subject" class="form-label">제목</label>
        <input type="text" class="form-control" name="title" id="title" value="{{ form.title.value|default_if_none:'' }}">
      </div>
      <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
      </div>

      <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
  </div>
{% endblock %}

templates/boards/post_list.html
{% extends 'layout/base.html' %}
{% block content %}
{% include 'store/head.html' %}
<!-- 네비게이션바 -->
{% include "layout/navbar.html" %}    
<!-- Header -->  
{% include 'store/header.html' %}

  <div class="container my-3">
    <div class="row my-3">
      {% comment %} <div class="col-6">
        <a href="{% url 'boards:post_create' %}" class="btn btn-primary">질문 등록하기</a>
      </div> {% endcomment %}
      <div class="col-6">
        <div class="input-group">
          <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
          </div>
        </div>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr class="text-center table-dark">
          <th>번호</th>
          <th style="width:50%">제목</th>
          <th>글쓴이</th>
          <th>작성일시</th>
        </tr>
      </thead>
      <tbody>
        {% if post_list %}
          {% for post in post_list %}
            <tr class="text-center">
              <td>{{post.id}}</td>
              <td class="text-start">
                <a href="{% url 'boards:detail' post.id %}">{{ post.title }}</a>
                {% if post.comment_set.count > 0 %}
                  <span class="text-danger small mx-2">{{ post.comment_set.count }}</span>
                {% endif %}
              </td>
              <td>{{ post.user.username }}</td>
              <!-- 글쓴이 추가 -->
              <td>{{ post.created_at }}</td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="4">게시글이 없습니다</td>
          </tr>
        {% endif %}
      </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
      <!-- 이전페이지 -->
      {% if post_list.has_previous %}
        <li class="page-item">
          <a class="page-link" data-page="?page={{ post_list.previous_page_number }}"  href="javascript:void(0)">이전</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
      {% endif %}
      <!-- 페이지리스트 -->

      {% for page_number in post_list.paginator.page_range %}
        {% if page_number >= post_list.number|add:-5 and page_number <= post_list.number|add:5%}
          {% if page_number == post_list.number %}
            <li class="page-item active" aria-current="page">
              <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}
      <!-- 다음페이지 -->
      {% if post_list.has_next %}
        <li class="page-item">
          <a class="page-link" data-page="{{ post_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
      {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'boards:post_create' %}" class="btn btn-primary">글 등록하기</a>
  </div>
  <form id="searchForm" method="get" action="{% url 'boards:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
  </form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}