api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from api.views import   CategoryViewSet, OrderViewSet, api_product, api_products, hello_world, hello_world_drf
from rest_framework.routers import DefaultRouter

#dev_48 app/urls.py 추가
app_name = 'api'

#dev_54
router = DefaultRouter()
router.register(r'categories',CategoryViewSet)
#dev_58
router.register("orders", OrderViewSet, basename="orders")

# /post/ 주소에 대해 URL Reverse 이름은 post-list이 등록
# /post/10/ 류의 주소에 대해 URL Reverse 이름은 post-detail이 등록


urlpatterns = [
    path("hello_world/", hello_world),
    path("hello_world_drf/", hello_world_drf),
    path("products/", api_products),#dev_49
    path("products/<int:pk>/", api_product),#dev_49
    path("products/", api_products),
    path("products/<int:pk>/", api_product),
    #path("categories/", MixinsCategories.as_view()),#dev_52
    #path("categories/<int:pk>/", MixinsCategory.as_view()),#dev_52         
    #path("categories/", APICategories.as_view()),#dev_53
    #path("categories/<int:pk>/", APICategory.as_view()),#dev_53
    #path("categories/", category_list),#dev_54
    #path("categories/<int:pk>/", category_detail),#dev_54
    path("", include(router.urls)),#dev_54
]

cart/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from cart import views

app_name = 'cart'

urlpatterns = [
    path("", views.cart_summary,name="cart_summary"),
    path("add/", views.cart_add,name="cart_add"), 
    path("delete/", views.cart_delete,name="cart_delete"), 
    path("update/", views.cart_update,name="cart_update"),      
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('store.urls')),
    path("home/", include('home.urls')),
    path("boards/", include('boards.urls')),
    path('account/', include('accounts.urls')),
    path("cart/", include('cart.urls')), 
    path("payment/", include('payment.urls')), #dev_41 settings 추가
    path('accounts/', include('allauth.urls')),#dev_46 
    path("api/", include("api.urls")),#dev_48
    path("auth/", include('djoser.urls')),#dev_57
    path("auth/", include('djoser.urls.jwt')),#dev_57
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index),
    path("ok/", views.ok), #home/ok/ 끝에 슬러시 주의 할것
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),  
    path('about/', views.about, name='about'),
    path('product/<int:product_id>', views.product, name='product'),
    path('category/<str:foo>', views.category, name='category'), #변수 foo 의 의미  참고:https://namu.wiki/w/foo
    path('category_summary/', views.category_summary, name='category_summary'),
    #dev_39
    path('search/', views.search, name='search'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):        
        return  f"{self.id} {self.name}" #dev_51
    
class Product(models.Model):
    name = models.CharField(max_length=100)
    #price = models.DecimalField(default=0,decimal_places=2,max_digits=6) #9999.99
    price = models.IntegerField(default=0) #9999.99
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    description = models.CharField(max_length=250,default='',blank=True, null=True)
    image = models.ImageField(upload_to='upload/product',blank=True, null=True)#dev_50 테스트를 위하여
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #판매 가능 여부(Add Sale stuff)       
    is_sale = models.BooleanField(default=False)
    sale_price = models.IntegerField(default=0) 
    
    def __str__(self):
        return f"{self.id} {self.name}" #dev_50 id 추가

home/views.py
from django.shortcuts import render

from django.shortcuts import render
from django.http import HttpResponse
 
# Create your views here.
def index(request):
    return render(request,"home/hello_world.html")

def ok(request):
    return HttpResponse("홈 OK 입니다")

store/views.py
from calendar import c
from itertools import product
from django.shortcuts import redirect, render

from store.models import Category, Product
from django.contrib import messages
from django.db.models import Q

# Create your views here.
def home(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    return render(request,'store/home.html',{'products':products,'categories':categories})

def about(request):
    return render(request,'store/about.html',{})

def product(request,product_id):
    product = Product.objects.get(id=product_id)
    return render(request, 'store/product.html', {'product':product})

def category(request, foo):
    #Replace Hyphens with Spaces

    foo = foo.replace('-',' ')
    #print(foo)

    # Grab the category from the url
    try:
        #Look up the category
        category = Category.objects.get(name=foo)
        print(category)
        
        products = Product.objects.filter(category=category)
        print(products)
        
        return render(request, 'store/category.html',{'products':products,'category':category,'categories':Category.objects.all })
    
    except:
        messages.success(request, ("카테고리가 존재하지 않습니다."))        
        return redirect('store:home')

def category_summary(request):
    categories = Category.objects.all()
    return render(request,'store/category_summary.html',{'categories':categories})

#dev_39
def search(request):
    #Determin if they filled out the form
    if request.method == 'POST':
        searched = request.POST['searched']
        
        searched = Product.objects.filter(Q(name__icontains=searched) | Q(description__icontains=searched) )
        print("서치=======", searched)

        #Test for null
        if not searched:
            messages.success(request,"해당 상품이 없습니다....")
            return render(request, "store/search.html",{})
        else:
            return render(request, "store/search.html",{'searched':searched})
    else:
        return render(request, "store/search.html",{})
   

templates/store/about.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}
  <!-- Head -->
  {% include 'store/head.html' %}
  <!-- 네비게이션바 -->
  {% include "layout/navbar.html" %}
  <!-- Header -->
  <header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">About us..</h1>
        <p class="lead fw-normal text-white-50 mb-0">
          어서오세요. 나의 쇼핑몰 입니다.
        </p>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="row">
      <center>
        <div class="col-8 mt-5">
          <p>모든 국민은 건강하고 쾌적한 환경에서 생활할 권리를 가지며, 국가와 국민은 환경보전을 위하여 노력하여야 한다. 국가는 청원에 대하여 심사할 의무를 진다. 국무총리는 국회의 동의를 얻어 대통령이 임명한다. 훈장등의 영전은 이를 받은 자에게만 효력이 있고, 어떠한 특권도 이에 따르지 아니한다. 대한민국의 경제질서는 개인과 기업의 경제상의 자유와 창의를 존중함을 기본으로 한다. 헌법재판소 재판관은 탄핵 또는 금고 이상의 형의 선고에 의하지 아니하고는 파면되지 아니한다. 국무총리·국무위원 또는 정부위원은 국회나 그 위원회에 출석하여 국정처리상황을 보고하거나 의견을 진술하고 질문에 응답할 수 있다. 모든 국민은 소급입법에 의하여 참정권의 제한을 받거나 재산권을 박탈당하지 아니한다. 국무회의는 정부의 권한에 속하는 중요한 정책을 심의한다. 체포·구속·압수 또는 수색을 할 때에는 적법한 절차에 따라 검사의 신청에 의하여 법관이 발부한 영장을 제시하여야 한다. 다만, 현행범인인 경우와 장기 3년 이상의 형에 해당하는 죄를 범하고 도피 또는 증거인멸의 염려가 있을 때에는 사후에 영장을 청구할 수 있다. 모든 국민은 양심의 자유를 가진다. 대법원장과 대법관이 아닌 법관은 대법관회의의 동의를 얻어 대법원장이 임명한다. 정당의 목적이나 활동이 민주적 기본질서에 위배될 때에는 정부는 헌법재판소에 그 해산을 제소할 수 있고, 정당은 헌법재판소의 심판에 의하여 해산된다. 대법관의 임기는 6년으로 하며, 법률이 정하는 바에 의하여 연임할 수 있다. 대통령은 제3항과 제4항의 사유를 지체없이 공포하여야 한다. 언론·출판에 대한 허가나 검열과 집회·결사에 대한 허가는 인정되지 아니한다. 국회는 정부의 동의없이 정부가 제출한 지출예산 각항의 금액을 증가하거나 새 비목을 설치할 수 없다. 국회의원의 선거구와 비례대표제 기타 선거에 관한 사항은 법률로 정한다. 정당은 그 목적·조직과 활동이 민주적이어야 하며, 국민의 정치적 의사형성에 참여하는데 필요한 조직을 가져야 한다. 위원은 정당에 가입하거나 정치에 관여할 수 없다. 대통령이 제1항의 기간내에 공포나 재의의 요구를 하지 아니한 때에도 그 법률안은 법률로서 확정된다. 형사피해자는 법률이 정하는 바에 의하여 당해 사건의 재판절차에서 진술할 수 있다. 국회의 정기회는 법률이 정하는 바에 의하여 매년 1회 집회되며, 국회의 임시회는 대통령 또는 국회재적의원 4분의 1 이상의 요구에 의하여 집회된다. 탄핵소추의 의결을 받은 자는 탄핵심판이 있을 때까지 그 권한행사가 정지된다. 선거운동은 각급 선거관리위원회의 관리하에 법률이 정하는 범위안에서 하되, 균등한 기회가 보장되어야 한다. 국회의원은 그 지위를 남용하여 국가·공공단체 또는 기업체와의 계약이나 그 처분에 의하여 재산상의 권리·이익 또는 직위를 취득하거나 타인을 위하여 그 취득을 알선할 수 없다. 근로조건의 기준은 인간의 존엄성을 보장하도록 법률로 정한다. 행정권은 대통령을 수반으로 하는 정부에 속한다. 대통령은 국무총리·국무위원·행정각부의 장 기타 법률이 정하는 공사의 직을 겸할 수 없다. 국회는 선전포고, 국군의 외국에의 파견 또는 외국군대의 대한민국 영역안에서의 주류에 대한 동의권을 가진다. 대통령은 조약을 체결·비준하고, 외교사절을 신임·접수 또는 파견하며, 선전포고와 강화를 한다. 대법원장의 임기는 6년으로 하며, 중임할 수 없다. 국회는 의장 1인과 부의장 2인을 선출한다. 누구든지 체포 또는 구속을 당한 때에는 적부의 심사를 법원에 청구할 권리를 가진다. 법관이 중대한 심신상의 장해로 직무를 수행할 수 없을 때에는 법률이 정하는 바에 의하여 퇴직하게 할 수 있다. 이 헌법공포 당시의 국회의원의 임기는 제1항에 의한 국회의 최초의 집회일 전일까지로 한다.</p>
        </div>
      </center>
    </div>
  </div>
  <!-- Footer-->
  {% include 'store/footer.html' %}
{% endblock content %}

templates/store/category.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}
  <!-- Head -->
  {% include 'store/head.html' %}
  <!-- 네비게이션바 -->
  {% include "layout/navbar.html" %}
  <!-- Header -->

  <header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">{{category}}</h1>
        <p class="lead fw-normal text-white-50 mb-0">Category Page</p>
      </div>
    </div>
  </header>

  <section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for product in products %}
          <div class="col mb-5">
            <div class="card h-100">
              {% if product.is_sale %}
                <!-- Sale badge-->
                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
              {% endif %}
              <!-- Product image-->
              <img class="card-img-top" style="object-fit:fill" src="{{product.image.url}}" alt="..."/>
              <!-- Product details-->
              <div class="card-body p-4">
                <div class="text-center">
                  <!-- Product name-->
                  <h5 class="fw-bolder">{{ product.name }}</h5>
                  <!-- Product reviews-->
                  <div class="d-flex justify-content-center small text-warning mb-2">
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                  </div>
                  <!-- Product price-->
                  {% if product.is_sale %}
                    <span class="text-muted text-decoration-line-through">$20.00</span>
                  {% endif %}
                  ${{ product.price }}
                </div>
              </div>
              <!-- Product actions-->
              <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center">
                  <a class="btn btn-outline-dark mt-auto" href="{% url 'store:product' product.id %}">View Product</a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
  {% include 'store/footer.html' %}
{%endblock content%}
<!-- Footer-->

templates/store/category_summary.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}

  {% include 'store/head.html' %}
  <div class="d-flex flex-column vh-100 justify-content-between">

    <!-- 네비게이션바 -->
    {% include "layout/navbar.html" %}

    <header class="bg-dark py-5">
      <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">카테고리</h1>
          <p class="lead fw-normal text-white-50 mb-0">Choose your Category Below..</p>
        </div>
      </div>
    </header>

    <br/>

    <div class="container">
      <div class="row">
        <center>
          <div class="col-8">
            <br/>
            <br/>
            {% for category in categories%}
              <h3>
                <a href="{% url 'store:category' category %}">{{ category}}</a>
              </h3>
            {% endfor %}
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
          </div>
        </center>
      </div>
    </div>
    <!-- Footer-->
    {% include 'store/footer.html' %}
  </div>
{%endblock content%}

templates/store/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">
      Copyright &copy; Your Website 2025
    </p>
  </div>
</footer>

templates/store/head.html
{% load static %}

<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <title>Shop Homepage - Start Bootstrap Template</title>
  <!-- Favicon-->
  <link rel="icon" type="image/x-icon" href="{% static 'store/assets/favicon.ico' %}"/>
  <!-- Bootstrap icons-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'store/css/styles.css' %}" rel="stylesheet"/>
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="{% static 'store/js/scripts.js' %}"></script>
</head>

templates/store/header.html
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">나의 쇼핑몰</h1>
      <p class="lead fw-normal text-white-50 mb-0">
        멋진 쇼핑몰을 만들어 보아요!!!
      </p>
    </div>
  </div>
</header>

templates/store/home.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}

    <!-- Head -->  
    {% include 'store/head.html' %}
    <!-- 네비게이션바 -->
    {% include "layout/navbar.html" %}    
    <!-- Header -->  
    {% include 'store/header.html' %}

    <!-- Section-->
    <section class="py-5">
      <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
          {% comment %} 이미지 처리 부분 {% endcomment %}
          
          {% for product in products %}
          <div class="col mb-5">
            <div class="card h-100">
              <!-- 세일 뱃지(sale badge) -->
              {% if  product.is_sale    %}
              <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">세일중</div>
              {% endif %}            

              <!-- Product image-->
              <img class="card-img-top" style="height:12rem;object-fit:fill;" src="{{ product.image.url}}" alt="..."/>
              <!-- Product details-->
              <div class="card-body p-4">
                <div class="text-center">
                  <!-- Product name-->
                  <h5 class="fw-bolder">{{product.name}}</h5>
                  <!-- Product price-->
                  
                  {% if product.is_sale %}
                    <span class="text-muted text-decoration-line-through">{{product.price}}</span>
                    {{product.sale_price}}원
                  {% else %}
                    {{product.price}}원
                  {% endif %}                  
                  <br>
                  {{product.description}}
                </div>
              </div>
              <!-- Product actions-->
              <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center">
                  <a class="btn btn-outline-dark mt-auto" href="{% url 'store:product' product.id %}">제품상세</a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

    <!-- Footer-->
    {% include 'store/footer.html' %}
{% endblock content %}

templates/store/product.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}

    <!-- Head -->  
    {% include 'store/head.html' %}
    <div class="d-flex flex-column vh-100 justify-content-between">
    <!-- 네비게이션바 -->
    {% include "layout/navbar.html" %}    
    {% comment %} <!-- Header -->  
    {% include 'store/header.html' %} {% endcomment %}

    <div class="container">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            {% comment %} dev_40 {% endcomment %}
            <img src="{{product.image.url}}" style="width: 100%;height:18.6rem;object-fit:fill;" class="img-fluid rounded-start" alt="..." />
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <center>
                <h5 class="card-title">{{product.name}}</h5>
                <p class="card-text">{{product.description}}</p>
    
                {% if product.is_sale%}
    
                <div class="d-flex justify-content-center small text-warning mb-2">
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                </div>
                <!-- Product price-->
                <strike> ${{ product.price }} </strike>
                &nbsp; ${{product.sale_price}} 
                {% else %} 
                  ${{ product.price }} 
                {%endif%}
                <br/><br>
                <!-- 수량 추가-->
                <div class="row justify-content-center">
                  <div class="col-md-2">갯수:</div>
                  <div class="col-md-2">
                    <select class="form-select form-select-sm" id="qty-cart" aria-label="Default select example">
                      <option value="1">1</option>
                      <option value="2">2</option>
                      <option value="3">3</option>
                      <option value="4">4</option>
                      <option value="5">5</option>
                    </select>
                  </div>
                </div>
                <!-- 수량 추가끝-->
                <br><br><a class="btn btn-secondary" href="{% url 'store:home' %}">홈으로</a>
                <button type="button" value="{{product.id}}" id="add-cart" class="btn btn-secondary">장바구니 담기</button>
              </center>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer-->
    {% include 'store/footer.html' %}
  </div>

  <script>
    $(document).on('click', '#add-cart',function(e){
      $.ajax({
        type:"POST",
        url:"{% url 'cart:cart_add' %}",
        data:{
          product_id: $('#add-cart').val(),
          product_qty: $('#qty-cart option:selected').text(),
          csrfmiddlewaretoken:'{{  csrf_token }}',
          action: 'post'
        },
        success : function(json){
          console.log(json)
          //$('#cart_quantity').text(json.qty)
          //추가 dev_38
          //location.reload();
          //dev_40
          location.href = "{% url 'cart:cart_summary' %}"
        },
        error : function(e){
          console.log(e)
        }
      })
    });
  </script>
  {% endblock content %}

templates/store/search.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}

  {% include 'store/head.html' %}
  <!-- 네비게이션바 -->
  {% include "layout/navbar.html" %}

  <div class="d-flex flex-column vh-100 justify-content-between">
    <header class="bg-dark py-5">
      <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">상품검색</h1>
          <p class="lead fw-normal text-white-50 mb-0">ind What You're Looking for</p>
        </div>
      </div>
    </header>

    <br/>

    <div class="container">
      <div class="row">
        <center>
          <div class="col-10">
            <br/>
            <br/>
            <div class="card">
              <div class="card-header">상품검색</div>
              <div class="card-body">
                <form action="{% url 'store:search' %}" method="POST">
                  {% csrf_token %}
                  <div class="mb-3">
                    <input type="text" class="form-control" placeholder="검색어를 넣으세요" name="searched"/>
                  </div>
                  <button type="submit" class="btn btn-secondary">상품검색</button>
                </form>
              </div>
            </div>
            <br/>
            <br/>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
              {% if searched %}
                <!-- You Searched for...{{searched}} <br /> -->
                {%for product in searched %}
                  <!-- {{product}}<br /> -->
                  <div class="col mb-5">
                    <div class="card h-100">
                      {% if product.is_sale %}
                        <!-- Sale badge-->
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                      {% endif %}
                      <!-- Product image-->
                      <img class="card-img-top" src="{{product.image.url}}" alt="..."/>
                      <!-- Product details-->
                      <div class="card-body p-4">
                        <div class="text-center">
                          <!-- Product name-->
                          <h5 class="fw-bolder">{{ product.name }}</h5>
                          <!-- Product reviews-->
                          <div class="d-flex justify-content-center small text-warning mb-2">
                            <div class="bi-star-fill"></div>
                            <div class="bi-star-fill"></div>
                            <div class="bi-star-fill"></div>
                            <div class="bi-star-fill"></div>
                            <div class="bi-star-fill"></div>
                          </div>
                          <!-- Product price-->
                          {% if product.is_sale %}
                            <span class="text-muted text-decoration-line-through">&nbsp;${{product.sale_price}}</span>
                          {% endif %}
                          ${{ product.price }}
                        </div>
                      </div>
                      <!-- Product actions-->
                      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center">
                          <a class="btn btn-outline-dark mt-auto" href="{% url 'store:product' product.id %}">View Product</a>
                        </div>
                      </div>
                    </div>
                  </div>
                  {%endfor%}
                  {%endif%}
                </div>
              </div>
            </center>
          </div>
        </div>
        <!-- Footer-->
        {% include 'store/footer.html' %}
      </div>
    {%endblock content%}