api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from api.views import   CategoryViewSet, OrderViewSet, api_product, api_products, hello_world, hello_world_drf
from rest_framework.routers import DefaultRouter

#dev_48 app/urls.py 추가
app_name = 'api'

#dev_54
router = DefaultRouter()
router.register(r'categories',CategoryViewSet)
#dev_58
router.register("orders", OrderViewSet, basename="orders")

# /post/ 주소에 대해 URL Reverse 이름은 post-list이 등록
# /post/10/ 류의 주소에 대해 URL Reverse 이름은 post-detail이 등록


urlpatterns = [
    path("hello_world/", hello_world),
    path("hello_world_drf/", hello_world_drf),
    path("products/", api_products),#dev_49
    path("products/<int:pk>/", api_product),#dev_49
    path("products/", api_products),
    path("products/<int:pk>/", api_product),
    #path("categories/", MixinsCategories.as_view()),#dev_52
    #path("categories/<int:pk>/", MixinsCategory.as_view()),#dev_52         
    #path("categories/", APICategories.as_view()),#dev_53
    #path("categories/<int:pk>/", APICategory.as_view()),#dev_53
    #path("categories/", category_list),#dev_54
    #path("categories/<int:pk>/", category_detail),#dev_54
    path("", include(router.urls)),#dev_54
]

boards/urls.py
from django.contrib import admin
from django.urls import path

from .views import base_views,comment_views,post_views
app_name = 'boards'

urlpatterns = [
   # base_views.py
   path("", base_views.index,name='index'), #boards/ 끝에 슬러시 주의 할것
   path('<int:post_id>/', base_views.detail, name='detail'),
   
   #comment_views.py
   path('comment/create/<int:post_id>/', comment_views.comment_create, name='reply_create'),
   path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
   path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),
   path('comment/vote/<int:comment_id>/', comment_views.comment_vote, name='comment_vote'),

   #post_views
   path('post/create/', post_views.post_create, name='post_create'),
   path('post/modify/<int:post_id>/', post_views.post_modify, name='post_modify'),
   path('post/delete/<int:post_id>/', post_views.post_delete, name='post_delete'),
   path('post/vote/<int:post_id>/', post_views.post_vote, name='post_vote'),

]

cart/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from cart import views

app_name = 'cart'

urlpatterns = [
    path("", views.cart_summary,name="cart_summary"),
    path("add/", views.cart_add,name="cart_add"), 
    path("delete/", views.cart_delete,name="cart_delete"), 
    path("update/", views.cart_update,name="cart_update"),      
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('store.urls')),
    path("home/", include('home.urls')),
    path("boards/", include('boards.urls')),
    path('account/', include('accounts.urls')),
    path("cart/", include('cart.urls')), 
    path("payment/", include('payment.urls')), #dev_41 settings 추가
    path('accounts/', include('allauth.urls')),#dev_46 
    path("api/", include("api.urls")),#dev_48
    path("auth/", include('djoser.urls')),#dev_57
    path("auth/", include('djoser.urls.jwt')),#dev_57
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

#dev_42
app_name = 'payment'

#dev_41 url 추가
# Create your views here.
urlpatterns = [
    path("payment_update_info/", views.payment_update_info, name="payment_update_info"), #dev_42 추가
    path("payment_success/", views.payment_success, name="payment_success"),
    path("payment_process_order/", views.payment_process_order, name="payment_process_order"),
    path("payment_order_list/", views.payment_order_list, name="payment_order_list"), #dev_45 추가
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),  
    path('about/', views.about, name='about'),
    path('product/<int:product_id>', views.product, name='product'),
    path('category/<str:foo>', views.category, name='category'), #변수 foo 의 의미  참고:https://namu.wiki/w/foo
    path('category_summary/', views.category_summary, name='category_summary'),
    #dev_39
    path('search/', views.search, name='search'),
]

boards/views/base_views.py
from django.http import HttpResponseNotAllowed
from django.utils import timezone   
from django.shortcuts import get_object_or_404, redirect, render

from boards.forms import CommentForm, PostForm
from boards.models import Comment, Post
from django.core.paginator import Paginator 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q

def index(request):
    page = request.GET.get('page', '1')  # 페이지 만약 넘어온값이 없으면 1페이지
    
    kw = request.GET.get('kw', '')  # 검색어 넘어온값이 없으면 ''(빈값으로)   
    post_list = Post.objects.order_by('-created_at')
    
    if kw:
        post_list = post_list.filter(
            Q(title__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw)|  # 내용 검색
            Q(comment__content__icontains=kw) |  # 답변 내용 검색
            Q(user__username__icontains=kw) |  # 게시글 글쓴이 검색
            Q(comment__user__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct() # 중복 제거

    paginator = Paginator(post_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'post_list': page_obj,'page': page, 'kw': kw} 

    return render(request, 'boards/post_list.html', context)

def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {'post': post}
    return render(request, 'boards/post_detail.html', context)

templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="ko">

  <body>

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}{% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- 자바스크립트 Start -->
    {% block script %}{% endblock %}
    <!-- 자바스크립트 End -->
    <!-- Bootstrap core JS-->
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'store/js/scripts.js' %}"></script> {% endcomment %}
  </body>

</html>

templates/layout/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      <!-- 필드 오류 -->
      {% if field.errors %}
        <div>
          <strong>{{ field.label }}</strong>
          {{ field.errors }}
        </div>
      {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
      <div>
        <strong>{{ error }}</strong>
      </div>
    {% endfor %}
  </div>
{% endif %}

templates/layout/message.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>메세지</strong>
      {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
  {%endif%}

templates/layout/navbar.html
<!-- Navigation-->
<div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="{% url 'store:home' %}">쇼핑몰</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:home' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:about' %}">About</a>
        </li>        
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">결재정보</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} #dev_45 추가 {% endcomment %}
            <li>
              <a class="dropdown-item" href="{% url 'payment:payment_order_list' %}">주문목록</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'payment:payment_update_info' %}">배송주소 변경</a>
            </li>
            {% comment %} <li>
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'update_info' %}"></a>
            </li> {% endcomment %}
          </ul>
        </li>  
        {% endif %}
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'accounts:logout' %}">{{user.username}}(로그아웃)</a>
          {% else %}
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:login'%}">로그인</a>
          {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'boards:index'%}">게시판</a>
        </li>
        <li>
          {% if not user.is_authenticated %}
            <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
          {% endif %}
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">카테고리</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'store:category_summary' %}">카테고리들</a>
            </li>
            <li>
              <hr class="dropdown-divider"/>
            </li>
            {% comment %} 카테고리 받아오기위한 추가 부분 {% endcomment %}
            {% if categories %}
              {% for category in categories %}
                <li>
                  <a class="dropdown-item" href="{% url 'store:category'  category.name %}">{{category.name}}</a>
                </li>
              {% endfor %}
            {% endif %}

          </ul>
        </li>
        {% comment %} dev_39 추가 {% endcomment %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:search' %}">검색</a>
        </li>
        {% comment %} dev_46 추가 {% endcomment %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:kakao_login' %}">소셜로그인</a>
        </li>
      </ul>
      <form class="d-flex">
        <a href="{% url 'cart:cart_summary'%}" class="btn btn-outline-dark">
          <i class="bi-cart-fill me-1"></i>
          Cart
          <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{cart|length}}</span>
        </a>
      </form>
    </div>
  </div>
</nav>
{% comment %} 추가 dev_38 {% endcomment %}
{% include 'layout/message.html' %}
</div>